alias: Porch - clear someone at door status
trigger:
  - entity_id: binary_sensor.porch_door_contact
    platform: state
    to: "on"
  - entity_id: binary_sensor.front_door_contact
    platform: state
    to: "on"
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.someone_at_door
