# base config
homeassistant:
  customize: !include customize.yaml
  auth_providers: !include auth_providers.yaml

default_config: # left deliberately empty (https://www.home-assistant.io/integrations/default_config/)

http:
  ip_ban_enabled: false
  login_attempts_threshold: 5

frontend:
  themes: !include_dir_merge_named themes

logger:
  default: warning

automation: !include_dir_list automation/
binary_sensor: !include_dir_list binary_sensors/
device_tracker: !include_dir_list device_trackers/
group: !include groups.yaml
input_number: !include_dir_named input_number/
input_boolean: !include_dir_named input_boolean/
input_select: !include_dir_named input_select/
input_datetime: !include_dir_named input_datetime/
input_text: !include_dir_named input_text/
light: !include_dir_merge_list light/
mqtt: !include mqtt.yaml
notify: !include_dir_merge_list notify/
plant: !include_dir_named plants/
proximity: !include_dir_named proximity/
recorder: !include recorder.yaml
script: !include_dir_named scripts/
scene: !include scenes.yaml
sensor: !include_dir_list sensors/
switch: !include_dir_merge_list switch/
timer: !include_dir_named timers/
wake_on_lan: # deliberately empty, switches on WOL integration

microsoft_graph:
  client_id: !secret microsoft_graph_client_id
  client_secret: !secret microsoft_graph_client_secret

panel_iframe:
  networkmap:
    title: "Zigbee Map"
    url: "/local/community/zigbee2mqtt_networkmap/map.html"
    icon: "mdi:graphql"

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    # parse_mode: html
    url: !secret base_url
    allowed_chat_ids:
      - !secret telegram_jamie_chat_id

tplink:
  discovery: false
  switch:
    - host: 192.168.0.12 # coffee machine plug

tts:
  - platform: google_translate
    base_url: !secret base_url

zigbee2mqtt_networkmap:
  topic: zigbee2mqtt
