trigger:
  - platform: state
    entity_id: switch.landing_switch, switch.lounge_switch_right
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: switch.landing_switch, switch.lounge_switch_right
    from: 'off'
    to: 'on'
action:
  service_template: >
      homeassistant.turn_{{ trigger.to_state.state }}
  data_template: 
    entity_id: group.landing_switches