alias: "Keep landing lightswitches in sync"
trigger:
  - platform: state
    entity_id: switch.landing_switch, switch.lounge_switch_right
    from: "on"
    to: "off"
    for: "00:00:02"
  - platform: state
    entity_id: switch.landing_switch, switch.lounge_switch_right
    from: "off"
    to: "on"
    for: "00:00:02"
action:
  service: "homeassistant.turn_{{ trigger.to_state.state }}"
  data:
    entity_id: group.landing_switches
