alias: Disable Zigbee joining by timer
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.zigbee_permit_join
action:
- service: mqtt.publish
  data:
    topic: zigbee2mqtt/bridge/config/permit_join
    payload: 'false'
- service: input_boolean.turn_off
  data:
    entity_id: input_boolean.zigbee_permit_join