alias: Turn Lights On at Sunset (if home)
description: ""
trigger:
  - below: 4
    entity_id: sun.sun
    platform: numeric_state
    attribute: elevation
condition:
  - condition: state
    entity_id: person.jamie
    state: home
  - condition: state
    entity_id: input_boolean.bedtime
    state: "off"
action:
  entity_id: switch.study_light_switch #study light
  service: switch.turn_on
