alias: Doorbell pressed
description: ""
trigger:
  platform: event
  event_type: esphome.rf_code_received
  event_data:
    code: b1e2c2
action:
  - choose:
      # IF it's December
      - conditions:
          - condition: template
            value_template: "{{ now().month == 12 }}"
        # Play Christmas chimes
        sequence:
          - service: media_player.play_media
            data:
              media_content_type: audio/mp3
              media_content_id: http://192.168.0.27:8123/local/mp3/sleighbells.mp3
              entity_id: media_player.karens_study_speaker
          - service: media_player.play_media
            data:
              media_content_type: audio/mp3
              media_content_id: http://192.168.0.27:8123/local/mp3/sleighbells.mp3
              entity_id: media_player.kitchen_speaker
    # Else play normal doorbell chimes
    default:
      - service: media_player.play_media
        data:
          media_content_type: audio/mp3
          media_content_id: http://192.168.0.27:8123/local/mp3/dingdong.mp3
          entity_id: media_player.kitchen_speaker
      - service: media_player.play_media
        data:
          media_content_type: audio/mp3
          media_content_id: http://192.168.0.27:8123/local/mp3/dingdong.mp3
          entity_id: media_player.karens_study_speaker

  - service: notify.mobile_app_jamie_s_phone
    data:
      title: "Ding dong!"
      message: "Someone is at the front door!"
      data:
        channel: Security # For devices on Android 8.0+ only
        importance: high
        ttl: 0
        priority: high

  - service: input_boolean.turn_on
    entity_id: input_boolean.someone_at_door

  - service: notify.alfred
    data:
      message: Someone is at the door!
      target:
        - "697513724034023464"
  - delay: 5
