alias: Kitchen - turn on coffee machine on workdays
trigger:
- at: 07:40:00
  platform: time
condition:
- condition: state
  entity_id: binary_sensor.workday_sensor
  state: 'on'
action:
- data: {}
  entity_id: script.turn_on_coffee_machine
  service: script.turn_on