alias: "Arrival scan"
initial_state: on
trigger:
  - platform: state
    entity_id: binary_sensor.front_door_contact
    to: "on"
  - platform: state
    entity_id: binary_sensor.kitchen_door_contact
    to: "on"
  - entity_id: binary_sensor.0x00158d00052d41b3_occupancy
    platform: state
    to: "on"
action:
  - service: script.scan_bt_arrive
