initial_state: 'on'
alias: 'Jamie home'
trigger:
# Trigger when any of their local trackers show home
- platform: state
  entity_id: 
    - device_tracker.c0_ee_fb_e1_dc_b8
    - device_tracker.jamie_bt_mobile_living_room
  to: 'home'
# Trigger when HA starts
- platform: homeassistant
  event: start
condition:
# As long as at least one tracker shows home
- condition: state
  entity_id: group.jamies_tracking_devices
  state: 'home'
action:
# Call the script we wrote above
- service: script.jamie_home