alias: Turn off bedtime when phone unplugged from AC
description: ''
trigger:
- entity_id: sensor.phone_charging
  from: ac
  platform: state
condition:
- after: 06:00:00
  condition: time
action:
- data: {}
  entity_id: input_boolean.bedtime
  service: input_boolean.turn_off