alias: Turn lights out when charging phone at night
description: ''
trigger:
- entity_id: sensor.phone_charging
  platform: state
  to: ac
condition:
  condition: or
  conditions:
    - after: '22:00:00'
      condition: time
    - before: '03:00:00'
      condition: time
action:
- data: {}
  entity_id: input_boolean.bedtime
  service: input_boolean.turn_on