alias: Turn things off at night
description: ''
trigger:
- entity_id: input_boolean.bedtime
  platform: state
  to: 'on'
condition: []
action:
- entity_id: light.study_light
  service: light.turn_off
- entity_id: media_player.spotify_jamie_weston
  service: media_player.media_pause
- entity_id: light.0x7cb03eaa0a050284_light #study light
  service: light.turn_off
- entity_id: switch.landing_switch #upstairs switch for landing light
  service: switch.turn_off
- entity_id: switch.lounge_switch_left #lounge light switch
  service: switch.turn_off