alias: Announce return (Jamie)
description: 'Announces Jamie''s return if the input boolean was previously set.'
trigger:
- entity_id: person.jamie
  event: enter
  platform: zone
  zone: zone.home
condition:
- condition: state
  entity_id: input_boolean.announce_return_jamie
  state: 'on'
action:
- service: media_player.play_media
  data:
    media_content_type: audio/mp3
    media_content_id: http://192.168.0.27:8123/local/mp3/dingdong.mp3
    entity_id: media_player.kitchen_speaker
- service: media_player.play_media
  data:
    media_content_type: audio/mp3
    media_content_id: http://192.168.0.27:8123/local/mp3/dingdong.mp3
    entity_id: media_player.karens_study_speaker
- data: {}
  entity_id: input_boolean.announce_return_jamie
  service: input_boolean.turn_off